service: serverless-example

plugins:
  - serverless-offline
  - serverless-dotenv-plugin
useDotenv: true
provider:
  name: aws
  runtime: nodejs20.x
  region: es-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - ec2:CreateNetworkInterface
      Resource: '*'
    - Effect: Allow
      Action:
        - ec2:CreateNetworkInterface
        - ec2:DescribeNetworkInterfaces
        - ec2:DeleteNetworkInterface
      Resource: '*'

environment:
  PG_HOST: ${env:PG_HOST}
  PG_DATABASE: ${env:PG_DATABASE}
  PG_USERNAME: ${env:PG_USERNAME}
  PG_PASSWORD: ${env:PG_PASSWORD}
  PG_PORT: ${env:PG_PORT}

functions:
  main:
    handler: dist/main.handler
    events:
      - http:
          method: ANY
          path: /
      - http:
          method: ANY
          path: '{proxy+}'
